# Generated by Django 3.2.9 on 2021-12-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
