# Generated by Django 3.2.9 on 2021-12-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_alter_wishlistitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
    ]
